### ISSUE TITLE
Getting issue in "navigateForward" functionality.

### ISSUE THREAD

**Issue by manjirirevclerx** [RevclerxTester/HybridDriven#4]
Step:
1.Login 
2.Use "navigateBack" function -> use "waiting"-> use "navigateForward" function.

In Report, when user use "navigateForward" and "navigateBack" functions, In report it shows navigate successfully
to "navigateForward" page and also having URL
![forword](https://user-images.githubusercontent.com/54529079/74330693-22b79800-4db8-11ea-9909-d3de3b228666.png)
 of forward page but its not able to load page for "navigateForward" so in screenshot 
it showing previous page and not able to perform all actions on web page so please change it.

**Comment by Ankushrevclerx** [comment]
Issue is fixed now, I will provide you batch file ASAP.

**Comment by Ankushrevclerx** [comment]
completd
